@startuml

class BaseConverter {
}

class DocxConverter extends BaseConverter {
    +get_subcommand() : str
    +get_description() : str
    +register(args_parser: Any) : None
    +convert_section(section: str, level: int) : Ret
    +convert_record_object_generic(record: Record_Object, level: int, translation: Optional[dict]) : Ret
    +finish() : Ret
}

package "Dependencies" {

    class trlc <<(M ,lightblue) module>>{
    }

    note bottom of trlc
        Use TRLC ast items:
        * Implicit_Null
        * Record_Object
        * Record_Reference
        * String_Literal
        * Expression
    end note


    class docx <<(M ,lightblue) module>>{
    }
    note bottom of docx
        Library for generating .docx files
    end note

    class DocxRenderer {
        + render(ast: Any) : str
    }

    class marko <<(M ,lightblue) module>> {
    }
    note bottom of marko
        Markdown Parser
    end note
}

DocxConverter ..> trlc
DocxConverter ..> docx
DocxConverter ..> DocxRenderer
DocxConverter ..> marko

@enduml