@startuml

abstract class AbstractConverter {
}
  
class BaseConverter extends AbstractConverter {
    +__init__(args: Any)
    +register(args_parser: Any) : None
    +set_render_cfg(render_cfg: RenderConfig) : None
    +begin() : Ret
    +enter_file(file_name: str) : Ret
    +leave_file(file_name: str) : Ret
    +convert_section(section: str, level: int) : Ret
    +convert_record_object(record: Record_Object, level: int) : Ret
    +finish() : Ret
    +convert_record_object_generic(record: Record_Object, level: int, translation: Optional[dict]) : Ret
}

enum RecordsPolicy {
    RECORD_CONVERT_ALL
    RECORD_SKIP_UNDEFINED
}

package "Dependencies" {
    class argparse  <<(M ,lightblue) module>> {
    }

    class Record_Object {
    }

    class Translator {

    }

    class RenderConfig {
    }
}

' Relationships
BaseConverter ..d.> RecordsPolicy
BaseConverter ..d.> Translator
BaseConverter ..d.> RenderConfig
BaseConverter ..d.> Record_Object
BaseConverter ..d.> argparse

@enduml