@startuml

class PlantUML {
    +__init__() : None
    +is_plantuml_file(diagram_path: str) : bool
    +generate(diagram_type: str, diagram_path: str, dst_path: str) : None
    +generate_to_bytes(diagram_type: str, diagram_source: str) : bytes
}


' Define external dependencies
package "Dependencies" {
    class requests <<(M ,lightblue) module>> {}
    class subprocess <<(M ,lightblue) module>> {}
}

' Relationships
PlantUML ..> requests
PlantUML ..> subprocess

@enduml
