@startuml

class BaseConverter {
}
class MarkdownConverter extends BaseConverter {
    +get_subcommand() : str
    +get_description() : str
    +register(args_parser: Any) : None
    +begin() : Ret
    +enter_file(file_name: str) : Ret
    +leave_file(file_name: str) : Ret
    +convert_section(section: str, level: int) : Ret
    +convert_record_object_generic(record: Record_Object, level: int, translation: Optional[dict]) : Ret
}


package "Dependencies" {

    class Record_Object {
    }

    class TrlcAstWalker {
    }
}

MarkdownConverter ..> Record_Object
MarkdownConverter ..> TrlcAstWalker

@enduml